### ISSUE TITLE
2.0 not stable? 

### ISSUE THREAD

**Issue by richlarcombe** [refinery/refinerycms-calendar#23]
Not sure where we're up to in terms of 2.0 ready'ness!

But just tried it out on a clean refinery 2.0.4 & postgres install:
Not knowing what to expect as trying this gem out for the first time, but is this helps anyone? 

* new 'venues' menu item appeared on the front end, 
* clicking this cause it to fall over with the following (even after venue data is in the db)

ActionView::Template::Error (undefined method `each' for nil:NilClass):
    1: <% content_for :body_content_left do %>
    2:   <ul id="venues">
    3:     <% @venues.each do |venue| %>
    4:       <li>
    5:         <%= link_to venue.name, refinery.calendar_venue_path(venue) %>
    6:       </li>
  /Users/rlarcombe/.rvm/gems/ruby-1.9.3-p125@refinery2.0/bundler/gems/refinerycms-calendar-1587e0550295/app/views/refinery/calendar/venues/index.html.erb:3:in `block in ___sers_rlarcombe__rvm_gems_ruby_______p____refinery____bundler_gems_refinerycms_calendar_____e________app_views_refinery_calendar_venues_index_html_erb__896554352859260886_70126231033580'
  actionpack (3.2.3) lib/action_view/helpers/capture_helper.rb:40:in `block in capture'
  actionpack (3.2.3) lib/action_view/helpers/capture_helper.rb:187:in `with_output_buffer'

 * next tried loggin in adding a venue, seem to save ok
 * then moved to add an event, fell over with this upon trying to save.

ActionView::Template::Error (PG::Error: ERROR:  non-integer constant in ORDER BY
LINE 1: ...ents".* FROM "refinery_calendar_events"  ORDER BY 'from' DES...
                                                             ^
: SELECT  "refinery_calendar_events".* FROM "refinery_calendar_events"  ORDER BY 'from' DESC LIMIT 20 OFFSET 0):
    1: <ul id='sortable_list'>
    2:   <%= render :partial => 'event', :collection => @events %>
    3: </ul>
    4: <%= render '/refinery/admin/sortable_list',
    5:             :continue_reordering => (local_assigns.keys.include?(:continue_reordering)) ? continue_reordering : true %>
  activerecord (3.2.3) lib/active_record/connection_adapters/postgresql_adapter.rb:1139:in `async_exec'

Assume i've either missed something or it's not yet ready for prime time?

**Comment by bricesanchez** [comment]
Refinery CMS 2.0 is deprecated, please use version 3.0
