### ISSUE TITLE
could not find gem

### ISSUE THREAD

**Issue by imidsac** [refinery/refinerycms-calendar#48]
Could not find gem 'refinerycms-calendar (~> 2.1.0) ruby' in any of the gem sources listed in your Gemfile or available on this machine.

**Comment by bricesanchez** [comment]
The latest Rubygem version looks like to be https://rubygems.org/gems/refinerycms-calendar/versions/2.0.4, please use the github repo source : 

```ruby
gem 'refinerycms-calendar', github: 'refinery/refinerycms-calendar', branch: 'master'
```

**Comment by imidsac** [comment]
same problem
Bundler could not find compatible versions for gem "refinerycms-core":
  In Gemfile:
    refinerycms-calendar (>= 0) ruby depends on
      refinerycms-core (~> 2.1.0) ruby

    refinerycms-core (~> 3.0.0) ruby

    refinerycms (>= 0) ruby depends on
      refinerycms-core (= 3.0.0) ruby

    refinerycms (>= 0) ruby depends on
      refinerycms-core (= 3.0.0) ruby

    refinerycms (>= 0) ruby depends on
      refinerycms-core (= 3.0.0) ruby

    refinerycms (>= 0) ruby depends on
      refinerycms-core (= 3.0.0) ruby

    refinerycms-core (>= 3.0.0, ~> 3.0) ruby

**Comment by bricesanchez** [comment]
`refinerycms-calendar` is not yet compatible with refinerycms 3.0.0. This extension needs to be updated.

**Comment by imidsac** [comment]
you apologized, how to do this?
