### ISSUE TITLE
Support for Refinery 3

### ISSUE THREAD

**Issue by wtca** [refinery/refinerycms-calendar#49]
Are there any plans to update this Gem to support Refinery 3.x?  Also, are there any known compatibility issues using the latest stable release of the calendar with Refinery 3?

**Comment by bricesanchez** [comment]
Hello @wtca, could you try this PR : https://github.com/refinery/refinerycms-calendar/pull/50 ?

**Comment by wtca** [comment]
Thank you @bricesanchez .  Am I also to assume that this gem will be compatible with Rails 4.2?

**Comment by bricesanchez** [comment]
Yes! And it's now merged on master
