### ISSUE TITLE
gem -v 3.0.0 doesn't work

### ISSUE THREAD

**Issue by pekakate** [refinery/refinerycms-calendar#51]
> Could not find gem 'refinerycms-calendar (~> 3.0) ruby' in any of the gem sources listed in your Gemfile or available on this machine.

If I try with older version: 2.0.4
https://rubygems.org/gems/refinerycms-calendar

then the problem:
refinerycms (~> 3.0) ruby depends on
      refinerycms-images (= 3.0.4) ruby depends on
        refinerycms-core (= 3.0.4) ruby

    refinerycms-calendar (>= 2.0.4, ~> 2.0) ruby depends on
      refinerycms-core (~> 2.0.3) ruby

I would like to use this extension. Thanks!

**Comment by bricesanchez** [comment]
You're right `refinerycms-calendar` has not yet been release on rubygems but it has been updated for Refinery CMS 3.0.0, please use the github source of the gem.

**Comment by pekakate** [comment]
Super! Thanks :)
this works:

gem 'refinerycms-calendar', github: 'refinery/refinerycms-calendar', branch: 'master'

**Comment by bricesanchez** [comment]
You're welcome :)
